# Google Cloud App Engine Configuration
runtime: python312

# Handlers for serving static files
handlers:
  # Serve admin dashboard at root
  - url: /
    static_files: admin/index.html
    upload: admin/index.html
    secure: always

  # Serve all admin files
  - url: /(.*)
    static_files: admin/\1
    upload: admin/.*
    secure: always

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 1
