# Google Cloud App Engine Configuration
runtime: python312

# Environment Variables
env_variables:
  SAK_BASE_URL: "http://wapi.saksolution.com"
  # NOTE: Do not commit secrets here. Deploy scripts generate a secrets-filled YAML at deploy time.
  SAK_SESSION_ID: "__SAK_SESSION_ID__"
  SAK_API_KEY: "__SAK_API_KEY__"
  INBOUND_SECRET: "__INBOUND_SECRET__"
  WEBHOOK_SECRET: "__WEBHOOK_SECRET__"
  PORT: "3005"

# Handlers for serving static files
handlers:
  # Service Worker
  - url: /sw.js
    static_files: dist-react/sw.js
    upload: dist-react/sw.js
    secure: always
    expiration: "0s"

  # Workbox files
  - url: /workbox-(.*)\.js
    static_files: dist-react/workbox-\1.js
    upload: dist-react/workbox-.*\.js
    secure: always

  # PWA files
  - url: /(manifest\.webmanifest|registerSW\.js)
    static_files: dist-react/\1
    upload: dist-react/(manifest\.webmanifest|registerSW\.js)
    secure: always


  # Static assets (JS, CSS, images)
  - url: /assets/(.*)
    static_files: dist-react/assets/\1
    upload: dist-react/assets/.*
    secure: always
    expiration: "7d"

  # Serve image files from dist-react root
  - url: /(.*\.svg)
    static_files: dist-react/\1
    upload: dist-react/.*\.svg
    secure: always
    expiration: "7d"
  - url: /(.*\.png)
    static_files: dist-react/\1
    upload: dist-react/.*\.png
    secure: always
    expiration: "7d"
  - url: /(.*\.jpe?g)
    static_files: dist-react/\1
    upload: dist-react/.*\.jpe?g
    secure: always
    expiration: "7d"

  # Root - serve React app
  - url: /
    static_files: dist-react/index.html
    upload: dist-react/index.html
    secure: always

  # All other routes - serve React app (for client-side routing)
  - url: /(.*)
    static_files: dist-react/index.html
    upload: dist-react/index.html
    secure: always

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 1
